//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGIdatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.Skills = new HashSet<Skill>();
            this.Users = new HashSet<User>();
        }
    
        public int VacancyID { get; set; }
        public int UserID { get; set; }
        public int Job_TypeID { get; set; }
        public System.DateTime Date_begin { get; set; }
        public System.DateTime Date_end { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinMonthsExperience { get; set; }
    
        public virtual Job_Type Job_Type { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
